### ISSUE TITLE
Add a friendly error when charset not supported

### ISSUE THREAD

**Issue by brunolouvem** [eugenehr/erlyconv#2]
## Purpose
Provide a users a frindly way of control software flow when erlyconv went used

## Changes
When a charset that not are supported is passed, erlyconv will response with a tuple error. eg.:
```erlang
1> erlyconv:from_unicode(xablau, "Xablau").
{error, not_supported_charset}
```

**Comment by eugenehr** [comment]
Done. Thx Bruno.
